import { DevianLogo, DiscordLogo, DribbleLogo, FacebookLogo, FlickrLogo, InstagramLogo, LinkedInLogo, NullIcon, PinterestLogo, QuoraLogo, RedditLogo, SkypeLogo, SnapchatLogo, SoundCloudLogo, SpotifyLogo, SteamLogo, TelegramLogo, TikTokLogo, TumblrLogo, TwitchLogo, TwitterLogo, VimeoLogo, WhatsAppLogo, YoutubeLogo } from "./svg";

export const SocialNetworks = [
    {
        name: 'Seleccione una aplicación',
        logo: <NullIcon className="" />,
        value: 0,
        urlHolder: 'https://example.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Devian Art',
        logo: <DevianLogo className="" />,
        value: 1,
        urlHolder: 'https://deviantart.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Discord',
        logo: <DiscordLogo className="" />,
        value: 2,
        urlHolder: 'https://discord.gg/profile',
        color1: '#FF0000',
        color2: '#282828',
    },
    {
        name: 'Dribbble',
        logo: <DribbleLogo className="" />,
        value: 3,
        urlHolder: 'hhttps://dribbble.com/profile',
        color1: '#FF0000',
        color2: '#282828',
    },
    {
        name: 'Facebook',
        logo: <FacebookLogo className="" />,
        value: 4,
        urlHolder: 'https://facebook.com/profile',
        color1: '#4267B2',
        color2: '#000000',
    },
    {
        name: 'Flickr',
        logo: <FlickrLogo className="" />,
        value: 5,
        urlHolder: 'https://flickr.com/people/profile',
        color1: '#4267B2',
        color2: '#000000',
    },
    {
        name: 'Instagram',
        logo: <InstagramLogo className="" />,
        value: 6,
        urlHolder: 'https://instagram.com/profile',
        color1: '#C13584',
        color2: '#833AB4',
    },
    {
        name: 'LinkedIn',
        logo: <LinkedInLogo className="" />,
        value: 7,
        urlHolder: 'https://linkedin.com/in/profile',
        color1: '#C13584',
        color2: '#833AB4',
    },
    {
        name: 'Pinterest',
        logo: <PinterestLogo className="" />,
        value: 8,
        urlHolder: 'https://pinterest.com.mx/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Quora',
        logo: <QuoraLogo className="" />,
        value: 9,
        urlHolder: 'https://quora.com/profile/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Reddit',
        logo: <RedditLogo className="" />,
        value: 10,
        urlHolder: 'https://reddit.com/r/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Skype',
        logo: <SkypeLogo className="" />,
        value: 11,
        urlHolder: 'https://join.skype.com/invite/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Snapchat',
        logo: <SnapchatLogo className="" />,
        value: 12,
        urlHolder: 'https://snapchat.com/p/profile',
        color1: '#000000',
        color2: '#833AB4',
    },
    {
        name: 'SoundCloud',
        logo: <SoundCloudLogo className="" />,
        value: 13,
        urlHolder: 'https://soundcloud.com/profile',
        color1: '#000000',
        color2: '#833AB4',
    },
    {
        name: 'Spotify',
        logo: <SpotifyLogo className="" />,
        value: 14,
        urlHolder: 'https://open.spotify.com/user/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Steam',
        logo: <SteamLogo className="" />,
        value: 15,
        urlHolder: 'https://steam.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Telegram',
        logo: <TelegramLogo className="" />,
        value: 16,
        urlHolder: 'https://telegram.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'TikTok',
        logo: <TikTokLogo className="" />,
        value: 17,
        urlHolder: 'https://tiktok.com/@profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Tumblr',
        logo: <TumblrLogo className="" />,
        value: 18,
        urlHolder: 'https://tumblr.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Twitch',
        logo: <TwitchLogo className="" />,
        value: 19,
        urlHolder: 'https://twitch.tv/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'Twitter',
        logo: <TwitterLogo className="" />,
        value: 20,
        urlHolder: 'https://twitter.com/profile',
        color1: '#1DA1F2',
        color2: '#14171A',
    },
    {
        name: 'Vimeo',
        logo: <VimeoLogo className="" />,
        value: 21,
        urlHolder: 'https://vimeo.com/profile',
        color1: '#1DA1F2',
        color2: '#14171A',
    },
    {
        name: 'WhatsApp',
        logo: <WhatsAppLogo className="" />,
        value: 22,
        urlHolder: 'https://whatsapp.com/profile',
        color1: '#E60023',
        color2: '#FFFFFF',
    },
    {
        name: 'YouTube',
        logo: <YoutubeLogo className="" />,
        value: 23,
        urlHolder: 'https://youtube.com/profile',
        color1: '#FF0000',
        color2: '#282828',
    },
]